[package]
name = "optimus-core"
version.workspace = true
edition.workspace = true

[dependencies]
memmap2 = { workspace = true }
pdf_oxide = "0.3.77"
rstar = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
lopdf = "0.45"

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "spatial_graph"
harness = false

[[bench]]
name = "ascii_grid"
harness = false
