[package]
name = "optimus-agent"
version.workspace = true
edition.workspace = true

[dependencies]
optimus-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
wasmtime = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
dotenv = "0.15"
tempfile = { workspace = true }
